// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/greet/[name].tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/lists/index.tsx";
import * as $6 from "./routes/lists/list-items/[id]/index.tsx";
import * as $7 from "./routes/lists/list-items/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/DeleteListItem.tsx";
import * as $$2 from "./islands/EditListItem.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/greet/[name].tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/lists/index.tsx": $5,
    "./routes/lists/list-items/[id]/index.tsx": $6,
    "./routes/lists/list-items/index.tsx": $7,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/DeleteListItem.tsx": $$1,
    "./islands/EditListItem.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
