// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/list-items/[id]/index.tsx";
import * as $3 from "./routes/api/list-items/db.ts";
import * as $4 from "./routes/api/list-items/index.tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/list-items/[id]/delete.ts";
import * as $7 from "./routes/lists/[id]/delete.ts";
import * as $8 from "./routes/lists/[id]/index.tsx";
import * as $9 from "./routes/lists/add.tsx";
import * as $10 from "./routes/lists/db.ts";
import * as $11 from "./routes/lists/index.tsx";
import * as $12 from "./routes/partials/add.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/DeleteListItem.tsx";
import * as $$2 from "./islands/EditListItem.tsx";
import * as $$3 from "./islands/ListAddForm.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/list-items/[id]/index.tsx": $2,
    "./routes/api/list-items/db.ts": $3,
    "./routes/api/list-items/index.tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/list-items/[id]/delete.ts": $6,
    "./routes/lists/[id]/delete.ts": $7,
    "./routes/lists/[id]/index.tsx": $8,
    "./routes/lists/add.tsx": $9,
    "./routes/lists/db.ts": $10,
    "./routes/lists/index.tsx": $11,
    "./routes/partials/add.tsx": $12,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/DeleteListItem.tsx": $$1,
    "./islands/EditListItem.tsx": $$2,
    "./islands/ListAddForm.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
